import { TankBgOffsetType } from "./defineTank";
import { DeepReadonly, readonly } from "vue";

/** 背景偏移：四级坦克 */
const levelFourFirstPlayerTankOffset: TankBgOffsetType = readonly({
    BEFORE_UP_WIDTH_OFFSET: -817,
    BEFORE_UP_HEIGHT_OFFSET: -1,
    AFTER_UP_WIDTH_OFFSET: -851,
    AFTER_UP_HEIGHT_OFFSET: -1,

    BEFORE_RIGHT_WIDTH_OFFSET: -885,
    BEFORE_RIGHT_HEIGHT_OFFSET: -1,
    AFTER_RIGHT_WIDTH_OFFSET: -919,
    AFTER_RIGHT_HEIGHT_OFFSET: -1,

    BEFORE_DOWN_WIDTH_OFFSET: -953,
    BEFORE_DOWN_HEIGHT_OFFSET: -1,
    AFTER_DOWN_WIDTH_OFFSET: -987,
    AFTER_DOWN_HEIGHT_OFFSET: -1,

    BEFORE_LEFT_WIDTH_OFFSET: -1021,
    BEFORE_LEFT_HEIGHT_OFFSET: -1,
    AFTER_LEFT_WIDTH_OFFSET: -1055,
    AFTER_LEFT_HEIGHT_OFFSET: -1,
});

/** 背景偏移：三级坦克 */
const levelThreeFirstPlayerTankOffset: TankBgOffsetType = readonly({
    BEFORE_UP_WIDTH_OFFSET: -545,
    BEFORE_UP_HEIGHT_OFFSET: -1,
    AFTER_UP_WIDTH_OFFSET: -579,
    AFTER_UP_HEIGHT_OFFSET: -1,

    BEFORE_RIGHT_WIDTH_OFFSET: -613,
    BEFORE_RIGHT_HEIGHT_OFFSET: -1,
    AFTER_RIGHT_WIDTH_OFFSET: -647,
    AFTER_RIGHT_HEIGHT_OFFSET: -1,

    BEFORE_DOWN_WIDTH_OFFSET: -681,
    BEFORE_DOWN_HEIGHT_OFFSET: -1,
    AFTER_DOWN_WIDTH_OFFSET: -715,
    AFTER_DOWN_HEIGHT_OFFSET: -1,

    BEFORE_LEFT_WIDTH_OFFSET: -749,
    BEFORE_LEFT_HEIGHT_OFFSET: -1,
    AFTER_LEFT_WIDTH_OFFSET: -783,
    AFTER_LEFT_HEIGHT_OFFSET: -1,
});

/** 背景偏移：二级坦克 */
const levelTwoFirstPlayerTankOffset: TankBgOffsetType = readonly({
    BEFORE_UP_WIDTH_OFFSET: -273,
    BEFORE_UP_HEIGHT_OFFSET: -1,
    AFTER_UP_WIDTH_OFFSET: -307,
    AFTER_UP_HEIGHT_OFFSET: -1,

    BEFORE_RIGHT_WIDTH_OFFSET: -341,
    BEFORE_RIGHT_HEIGHT_OFFSET: -1,
    AFTER_RIGHT_WIDTH_OFFSET: -375,
    AFTER_RIGHT_HEIGHT_OFFSET: -1,

    BEFORE_DOWN_WIDTH_OFFSET: -409,
    BEFORE_DOWN_HEIGHT_OFFSET: -1,
    AFTER_DOWN_WIDTH_OFFSET: -443,
    AFTER_DOWN_HEIGHT_OFFSET: -1,

    BEFORE_LEFT_WIDTH_OFFSET: -477,
    BEFORE_LEFT_HEIGHT_OFFSET: -1,
    AFTER_LEFT_WIDTH_OFFSET: -511,
    AFTER_LEFT_HEIGHT_OFFSET: -1,
});

/** 背景偏移：一级坦克 */
const levelOneFirstPlayerTankOffset: TankBgOffsetType = readonly({
    BEFORE_UP_WIDTH_OFFSET: -1,
    BEFORE_UP_HEIGHT_OFFSET: -1,
    AFTER_UP_WIDTH_OFFSET: -35,
    AFTER_UP_HEIGHT_OFFSET: -1,

    BEFORE_RIGHT_WIDTH_OFFSET: -69,
    BEFORE_RIGHT_HEIGHT_OFFSET: -1,
    AFTER_RIGHT_WIDTH_OFFSET: -103,
    AFTER_RIGHT_HEIGHT_OFFSET: -1,

    BEFORE_DOWN_WIDTH_OFFSET: -137,
    BEFORE_DOWN_HEIGHT_OFFSET: -1,
    AFTER_DOWN_WIDTH_OFFSET: -171,
    AFTER_DOWN_HEIGHT_OFFSET: -1,

    BEFORE_LEFT_WIDTH_OFFSET: -205,
    BEFORE_LEFT_HEIGHT_OFFSET: -1,
    AFTER_LEFT_WIDTH_OFFSET: -239,
    AFTER_LEFT_HEIGHT_OFFSET: -1,
});


const p1BgOffsets: DeepReadonly<TankBgOffsetType[]> = readonly([
    levelOneFirstPlayerTankOffset, levelTwoFirstPlayerTankOffset,
    levelThreeFirstPlayerTankOffset, levelFourFirstPlayerTankOffset,
]);

export { p1BgOffsets };